### PR TITLE
llvm: Add binaries instead of appending path

### PR DESCRIPTION
**Pull request by Ash258**
- Closes lukesampson/scoop#3343

lukesampson/scoop#3342

Co-authored-by: Daan De Meyer <daan.j.demeyer@gmail.com>

### CODE REVIEW

**Comment by r15ch13** [comment]
Sorry @DaanDeMeyer I somehow messed up the co-authored-by 😢

**Comment by Ash258** [comment]
@r15ch13 Use [refined github](https://github.com/sindresorhus/refined-github) They have nice feature for merging PRs (next to other awesome features)

A

**Comment by r15ch13** [comment]
@Ash258 I have that already installed :smile:
But I guess the co-authored-by is valid, only GitHub is not showing it.

image

vs

image

**Comment by DaanDeMeyer** [comment]
I don't really mind. Thanks for merging the PR!

**Pull request merged**
