### PR TITLE
serve: Add description

### PR DESCRIPTION
**Pull request by philippgille**

### CODE REVIEW

**Comment by h404bi** [comment]
https://github.com/scoopinstaller/scoop-main/pull/31 I'm sorry but I was faster 😄

**Comment by h404bi** [comment]
@r15ch13 there are two `desc` now.. you shouldn't merge this. :smile:

**Comment by r15ch13** [comment]
It's from the project owner himself. :grin:
But I should have changed the commit to `Update description`. Now its to late 🤷‍♂ :smile:

**Comment by Ash258** [comment]
At least you can open new PR which format and organize that manifest and could also remove that unneeded notes :D

**Comment by r15ch13** [comment]
Oh crap, those where additions ...

**Comment by philippgille** [comment]
Sorry for the confusion (I didn't know about the other PR, which wasn't merged yet) and thanks for sorting this out!

**Pull request merged**
